language: node_js
sudo: false
dist: trusty
node_js:
  - "4"
  - "5"
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - libcairo2-dev 
      - libjpeg8-dev 
      - libpango1.0-dev 
      - libgif-dev 
      - build-essential 
      - g++-4.8
env:
  - CXX=g++-4.8
before_script:
  - npm install -g mocha